### ISSUE TITLE
Unable to reproduce this experiment

### ISSUE THREAD

**Issue by GitHubDiom** [aFuerst/faascache-sim#1]
Hi Alexander,
I am trying to reproduce the experiments of the ASPLOS paper.

The AzureFunctionDataset are stored on path `/home/jairwu/data/azure/functions/` like:
![image](https://user-images.githubusercontent.com/19339686/117393898-ad3d6780-af27-11eb-90f5-464e5f1ee0de.png)

Then I try to run the `trace_split_funcs.py`. Follows are the changes i have made:
```python
line 8: store = "/home/jairwu/data/azure/functions/trace_pckl/"
line 11: datapath = "/home/jairwu/data/azure/functions/"
```
But it seems unable to reproduce, I got the errors:
```shell
(faascache-sim) [jairwu@kubemaster faascache-sim]$ python code/split/gen/trace_split_funcs.py 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jairwu/anaconda3/envs/faascache-sim/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jairwu/anaconda3/envs/faascache-sim/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "code/split/gen/trace_split_funcs.py", line 45, in trace_row
    with open(out_pth, "w+b") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jairwu/data/azure/functions/trace_pckl/520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96b3d7f85d46209b7872.pckl'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "code/split/gen/trace_split_funcs.py", line 80, in <module>
    p.map(trace_row, joined.iterrows())
  File "/home/jairwu/anaconda3/envs/faascache-sim/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jairwu/anaconda3/envs/faascache-sim/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/jairwu/data/azure/functions/trace_pckl/520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96b3d7f85d46209b7872.pckl'
```

The question is:
1. How do get the file `/520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96b3d7f85d46209b7872.pckl`?
2. It this simulator rely on the `FaasCache OpenWhisk` you mentioned on the paper? Because the repository `FaasCache OpenWhisk` seems does not existed

Thank you

**Comment by aFuerst** [comment]
Hello there. This is the simulator from the paper, yes.

You're getting that error because `/home/jairwu/data/azure/functions/` exists, but not `/home/jairwu/data/azure/functions/trace_pckl/`.
And the `520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96b3d7f85d46209b7872` in that pickle file name is a unique function hash taken from the original trace files
